name: Daily Rental Status Check

on:
  schedule:
    # Runs every day at 00:15 Asia/Kathmandu
    - cron: '15 18 * * *'
  workflow_dispatch: # allows manual trigger

jobs:
  rentalStatus:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your repository
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

        # Step 4: Write Firebase service account key
      - name: Write Firebase service account key
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > serviceAccountKey.json


      # Step 5: Run your Node.js script
      - name: Run Rental Status Script
        run: node scripts/checkRentalStatus.js
